# Generated by Django 5.0.2 on 2024-03-20 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(max_length=10)),
                ('user', models.CharField(max_length=50)),
                ('payment_mode', models.CharField(max_length=50)),
                ('payment_date', models.DateField(default=datetime.datetime(2024, 3, 20, 13, 24, 38, 212237))),
            ],
        ),
    ]
