# Generated by Django 5.0.2 on 2024-03-20 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 20, 16, 29, 38, 611578)),
        ),
    ]
