# Generated by Django 5.0.2 on 2024-03-20 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.TimeField(default=datetime.time(16, 29, 55, 209182)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 20, 16, 29, 55, 209183)),
        ),
    ]
