# Generated by Django 5.0.2 on 2024-03-21 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_order_expected_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected',
            field=models.TimeField(default=datetime.time(16, 39, 14, 803718)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 15, 54, 14, 794133)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(default=datetime.time(15, 54, 14, 794133)),
        ),
    ]
