# Generated by Django 5.0.2 on 2024-03-28 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_order_expected_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancelled_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('cancelled_date', models.DateField(default=datetime.datetime(2024, 3, 28, 13, 58, 9, 452482))),
                ('cancelled_time', models.TimeField(default=datetime.time(13, 58, 9, 452482))),
                ('reason', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected',
            field=models.TimeField(default=datetime.time(14, 43, 9, 452482)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 28, 13, 58, 9, 436859)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(default=datetime.time(13, 58, 9, 436858)),
        ),
    ]
