# Generated by Django 5.0.2 on 2024-04-10 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_cancelled_order_order_cancelled_alter_order_expected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dilivered_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('dilivery_date', models.DateField(default=datetime.datetime(2024, 4, 10, 11, 52, 12, 86707))),
                ('dilivery_time', models.TimeField(default=datetime.time(11, 52, 12, 86707))),
            ],
        ),
        migrations.AlterField(
            model_name='cancelled_order',
            name='cancelled_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 10, 11, 52, 12, 86707)),
        ),
        migrations.AlterField(
            model_name='cancelled_order',
            name='cancelled_time',
            field=models.TimeField(default=datetime.time(11, 52, 12, 86707)),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected',
            field=models.TimeField(default=datetime.time(12, 37, 12, 85708)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 10, 11, 52, 12, 67718)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(default=datetime.time(11, 52, 12, 67717)),
        ),
    ]
