# Generated by Django 5.0.2 on 2024-04-11 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_product_available_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='list',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cancelled_order',
            name='cancelled_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 11, 11, 35, 5, 600033)),
        ),
        migrations.AlterField(
            model_name='cancelled_order',
            name='cancelled_time',
            field=models.TimeField(default=datetime.time(11, 35, 5, 600033)),
        ),
        migrations.AlterField(
            model_name='dilivered_order',
            name='dilivery_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 11, 11, 35, 5, 601033)),
        ),
        migrations.AlterField(
            model_name='dilivered_order',
            name='dilivery_time',
            field=models.TimeField(default=datetime.time(11, 35, 5, 601032)),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected',
            field=models.TimeField(default=datetime.time(12, 20, 5, 599020)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 11, 11, 35, 5, 581038)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(default=datetime.time(11, 35, 5, 581038)),
        ),
    ]
