# Generated by Django 5.0.2 on 2024-04-11 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_product_list_alter_cancelled_order_cancelled_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='admin', max_length=60)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('date', models.DateField(default=datetime.datetime(2024, 4, 11, 15, 0, 41, 7011))),
                ('time', models.TimeField(default=datetime.time(15, 0, 41, 7011))),
            ],
        ),
        migrations.AlterField(
            model_name='cancelled_order',
            name='cancelled_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 11, 15, 0, 41, 6012)),
        ),
        migrations.AlterField(
            model_name='cancelled_order',
            name='cancelled_time',
            field=models.TimeField(default=datetime.time(15, 0, 41, 6012)),
        ),
        migrations.AlterField(
            model_name='dilivered_order',
            name='dilivery_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 11, 15, 0, 41, 6012)),
        ),
        migrations.AlterField(
            model_name='dilivered_order',
            name='dilivery_time',
            field=models.TimeField(default=datetime.time(15, 0, 41, 6012)),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected',
            field=models.TimeField(default=datetime.time(15, 45, 41, 5012)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 11, 15, 0, 40, 985266)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(default=datetime.time(15, 0, 40, 985266)),
        ),
    ]
