# Generated by Django 5.0.2 on 2024-04-19 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_customer_profile_pic_alter_activity_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 19, 12, 25, 2, 477247)),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.TimeField(default=datetime.time(12, 25, 2, 477246)),
        ),
        migrations.AlterField(
            model_name='cancelled_order',
            name='cancelled_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 19, 12, 25, 2, 476248)),
        ),
        migrations.AlterField(
            model_name='cancelled_order',
            name='cancelled_time',
            field=models.TimeField(default=datetime.time(12, 25, 2, 476248)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='dilivered_order',
            name='dilivery_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 19, 12, 25, 2, 477247)),
        ),
        migrations.AlterField(
            model_name='dilivered_order',
            name='dilivery_time',
            field=models.TimeField(default=datetime.time(12, 25, 2, 477246)),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected',
            field=models.TimeField(default=datetime.time(13, 10, 2, 475228)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 19, 12, 25, 2, 453593)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(default=datetime.time(12, 25, 2, 453592)),
        ),
    ]
