# Generated by Django 5.0.2 on 2024-04-19 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_customer_inactive_alter_activity_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='inactive',
            new_name='block',
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 19, 12, 42, 6, 573100)),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.TimeField(default=datetime.time(12, 42, 6, 573100)),
        ),
        migrations.AlterField(
            model_name='cancelled_order',
            name='cancelled_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 19, 12, 42, 6, 572100)),
        ),
        migrations.AlterField(
            model_name='cancelled_order',
            name='cancelled_time',
            field=models.TimeField(default=datetime.time(12, 42, 6, 572100)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='dilivered_order',
            name='dilivery_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 19, 12, 42, 6, 572100)),
        ),
        migrations.AlterField(
            model_name='dilivered_order',
            name='dilivery_time',
            field=models.TimeField(default=datetime.time(12, 42, 6, 572100)),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected',
            field=models.TimeField(default=datetime.time(13, 27, 6, 571100)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 19, 12, 42, 6, 550885)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(default=datetime.time(12, 42, 6, 550885)),
        ),
    ]
