# Generated by Django 5.0.2 on 2024-03-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('items', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('net', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
        ),
    ]
